name: stemxplore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1
  google_nav_bar: ^5.0.7
  http: ^1.5.0
  video_player: ^2.10.1
  curved_navigation_bar: ^1.0.6
  shared_preferences: ^2.5.4
  flutter_localization: ^0.3.3
  provider: ^6.1.5+1
  video_thumbnail: ^0.5.6
  google_fonts: ^6.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flag/
